# Generated by Django 5.2.7 on 2025-10-04 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0002_crew_train_traintype_order_route_journey_ticket_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="train",
            name="train_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="stations.traintype",
            ),
        ),
    ]
