# Generated by Django 5.2.7 on 2025-10-08 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0004_rename_cargo_number_train_cargo_alter_order_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="stations.order",
            ),
        ),
    ]
