# Generated by Django 5.2.7 on 2025-10-09 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0005_alter_ticket_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="journey",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tickets",
                to="stations.journey",
            ),
        ),
    ]
