# Generated by Django 5.2.7 on 2025-10-09 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0006_alter_ticket_journey"),
    ]

    operations = [
        migrations.AddField(
            model_name="train",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
